CREATE DATABASE IF NOT EXISTS springmybatis DEFAULT CHARSET utf8;

CREATE TABLE t_user (
  USER_ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_NAME CHAR(30) NOT NULL,
  USER_PASSWORD CHAR(10) NOT NULL,
  PRIMARY KEY (USER_ID),
  KEY IDX_NAME (USER_NAME)
) ENGINE=INNODB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;